# Generated by Django 5.0 on 2024-10-14 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor_profile.division'),
        ),
    ]
