# Generated by Django 5.0 on 2024-10-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0003_alter_doctorprofile_division'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloseDay',
        ),
    ]
